name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]
        redis-version: [4, 5, 6, 7]

    steps:
      - uses: actions/checkout@v4
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go run gotest.tools/gotestsum@latest
